import type { CVLanguage } from "./store/cvStore";

const englishStrings = {
  languageNames: {
    en: "English",
    de: "German",
    pl: "Polish",
    fr: "French",
  },
  editor: {
    builder: "CV builder",
    restart: "Restart",
    restartAria: "Restart and clear saved CV data",
    save: "Save",
    import: "Import",
    importAria: "Import saved CV data",
    personalDetails: "Personal details",
    additionalDetails: "Experience & more",
    personalDetailsIntro: "Add the details employers need to contact you.",
    additionalDetailsIntro:
      "Add your experience, education, and other CV sections.",
    resumeLanguage: "Resume language",
    fontSize: "Font size",
    sidebarInset: "Inset sidebar",
    photo: "Profile photo",
    optional: "(optional)",
    photoFormats: "JPG, PNG, or WebP. Maximum 15 MB.",
    optimizingImage: "Optimizing image...",
    changePhoto: "Change photo",
    addPhoto: "Add photo",
    removePhoto: "Remove photo",
    photoShape: "Photo shape",
    circle: "Circle",
    rectangle: "Rectangle",
    rounded: "Rounded",
    photoSize: "Photo size",
    border: "Border",
    choosePhoto: "Choose a profile photo",
    chooseJpgPngWebp: "Choose a JPG, PNG, or WebP image.",
    imageTooLarge: "Choose an image smaller than 15 MB.",
    imagePreparationFailed:
      "This image could not be prepared. Try another file.",
    cropSaveFailed: "The crop could not be saved. Adjust it and try again.",
    identity: "Identity",
    requiredFields: "(Required fields marked *)",
    firstName: "First name",
    firstNameExample: "e.g. Alex",
    lastName: "Last name",
    lastNameExample: "e.g. Morgan",
    professionalTitle: "Professional title",
    dateOfBirth: "Date of birth",
    contact: "Contact",
    emailAddress: "Email address",
    phoneNumber: "Phone number",
    location: "Location",
    streetAddress: "Street address",
    streetPlaceholder: "Street and number (optional)",
    city: "City",
    postalCode: "Postal code",
    postalCodeExample: "e.g. M5V 2T6",
    country: "Country",
    countryExample: "e.g. Canada",
    onlinePresence: "Online presence",
    linkedInProfile: "LinkedIn profile",
    websitePortfolio: "Personal website or portfolio",
    next: "Next",
    summary: "Professional summary",
    summaryLabel: "Summary",
    summaryPlaceholder: "A short introduction to your experience and strengths",
    workExperience: "Work experience",
    sortedByDate: "Sorted automatically by date, from newest to oldest.",
    position: "Position {number}",
    remove: "Remove",
    jobTitle: "Job title",
    employer: "Employer",
    startDate: "Start date",
    endDate: "End date",
    responsibilities: "Responsibilities and achievements",
    addWorkExperience: "Add work experience",
    education: "Education",
    educationEntry: "Education {number}",
    school: "School or institution",
    degree: "Degree or qualification",
    fieldOfStudy: "Field of study",
    details: "Details",
    addEducation: "Add education",
    skills: "Skills",
    skillsPlaceholder: "Add skills separated by commas",
    languages: "Languages",
    language: "Language",
    languageExample: "e.g. English",
    proficiency: "Proficiency",
    proficiencyExample: "Native, fluent, B2, conversational",
    reorderLanguage: "Reorder language {number}",
    dragToReorder: "Drag to reorder",
    addLanguage: "Add language",
    projects: "Projects",
    project: "Project {number}",
    projectName: "Project name",
    yourRole: "Your role",
    projectUrl: "Project URL",
    addProject: "Add project",
    courses: "Courses & certifications",
    course: "Course {number}",
    courseName: "Course or certification",
    provider: "Provider",
    completionDate: "Completion date",
    shortDescription: "Short description",
    coursePlaceholder: "Briefly describe what you learned",
    addCourse: "Add course",
    interests: "Interests & hobbies",
    interestsPlaceholder: "Add interests & hobbies separated by commas",
    consent: "Consent for personal data processing",
    consentDescription:
      "This clause informs the company that you agree to the processing of your personal data for recruitment and hiring purposes.",
    consentStatement: "Consent statement",
    consentPlaceholder:
      "I consent to the processing of my personal data for recruitment purposes...",
    back: "Back",
    invalidImport: "The imported file is not valid CV data.",
    cropTitle: "Crop profile photo",
    cropInstructions: "Drag to reposition, then adjust the zoom.",
    closeCrop: "Close crop dialog",
    zoom: "Zoom",
    cancel: "Cancel",
    processing: "Processing...",
    usePhoto: "Use photo",
  },
  preview: {
    preparing: "Preparing...",
    exportPdf: "Export as PDF",
    liveDocument: "Live document",
    cvPreview: "CV Preview",
    colorway: "Colorway",
    cvColorway: "CV colorway",
    chooseCustomColor: "Choose a custom color",
    chooseCustomCvColor: "Choose a custom CV colorway",
    font: "Font",
    cvFont: "CV font style",
    fontName: "{font} font",
    templates: "CV templates",
    cvPages: "CV preview pages",
    previousCvPage: "Previous CV page",
    previousPage: "Previous page",
    nextCvPage: "Next CV page",
    nextPage: "Next page",
  },
  colorNames: {
    navy: "Navy",
    forest: "Forest",
    burgundy: "Burgundy",
    charcoal: "Charcoal",
    teal: "Teal",
    custom: "Custom",
  },
  fontNames: {
    formal: "Formal",
    modern: "Modern",
    humanist: "Humanist",
  },
  templateNames: {
    modern: "Modern",
    classic: "Classic",
    sidebar: "Sidebar",
  },
  templateNotes: {
    modern: "Clean and structured",
    classic: "Traditional and refined",
    sidebar: "Compact and editorial",
  },
} as const;

type WidenStrings<T> = {
  [Key in keyof T]: T[Key] extends string
    ? string
    : T[Key] extends object
      ? WidenStrings<T[Key]>
      : never;
};

type AppStrings = WidenStrings<typeof englishStrings>;

export const appStrings: Record<CVLanguage, AppStrings> = {
  en: englishStrings,
  de: {
    languageNames: {
      en: "Englisch",
      de: "Deutsch",
      pl: "Polnisch",
      fr: "Französisch",
    },
    editor: {
      builder: "Lebenslauf-Editor",
      restart: "Zurücksetzen",
      restartAria: "Zurücksetzen und gespeicherten Lebenslauf löschen",
      save: "Speichern",
      import: "Importieren",
      importAria: "Gespeicherten Lebenslauf importieren",
      personalDetails: "Persönliche Angaben",
      additionalDetails: "Berufserfahrung & mehr",
      personalDetailsIntro:
        "Fügen Sie die Kontaktdaten hinzu, die Arbeitgeber benötigen.",
      additionalDetailsIntro:
        "Fügen Sie Berufserfahrung, Ausbildung und weitere Abschnitte hinzu.",
      resumeLanguage: "Lebenslaufsprache",
      fontSize: "Schriftgröße",
      sidebarInset: "Seitenleiste einrücken",
      photo: "Profilfoto",
      optional: "(optional)",
      photoFormats: "JPG, PNG oder WebP. Maximal 15 MB.",
      optimizingImage: "Bild wird optimiert...",
      changePhoto: "Foto ändern",
      addPhoto: "Foto hinzufügen",
      removePhoto: "Foto entfernen",
      photoShape: "Fotoform",
      circle: "Kreis",
      rectangle: "Rechteck",
      rounded: "Abgerundet",
      photoSize: "Fotogröße",
      border: "Rahmen",
      choosePhoto: "Profilfoto auswählen",
      chooseJpgPngWebp: "Wählen Sie ein JPG-, PNG- oder WebP-Bild.",
      imageTooLarge: "Wählen Sie ein Bild mit weniger als 15 MB.",
      imagePreparationFailed:
        "Dieses Bild konnte nicht vorbereitet werden. Versuchen Sie ein anderes.",
      cropSaveFailed:
        "Der Zuschnitt konnte nicht gespeichert werden. Passen Sie ihn an und versuchen Sie es erneut.",
      identity: "Persönliche Angaben",
      requiredFields: "(Pflichtfelder sind mit * markiert)",
      firstName: "Vorname",
      firstNameExample: "z. B. Alex",
      lastName: "Nachname",
      lastNameExample: "z. B. Morgan",
      professionalTitle: "Berufsbezeichnung",
      dateOfBirth: "Geburtsdatum",
      contact: "Kontakt",
      emailAddress: "E-Mail-Adresse",
      phoneNumber: "Telefonnummer",
      location: "Standort",
      streetAddress: "Straße und Hausnummer",
      streetPlaceholder: "Straße und Hausnummer (optional)",
      city: "Stadt",
      postalCode: "Postleitzahl",
      postalCodeExample: "z. B. 10115",
      country: "Land",
      countryExample: "z. B. Deutschland",
      onlinePresence: "Online-Auftritt",
      linkedInProfile: "LinkedIn-Profil",
      websitePortfolio: "Persönliche Website oder Portfolio",
      next: "Weiter",
      summary: "Berufliches Profil",
      summaryLabel: "Profil",
      summaryPlaceholder: "Kurze Vorstellung Ihrer Erfahrung und Stärken",
      workExperience: "Berufserfahrung",
      sortedByDate: "Automatisch nach Datum sortiert, neueste zuerst.",
      position: "Position {number}",
      remove: "Entfernen",
      jobTitle: "Berufsbezeichnung",
      employer: "Arbeitgeber",
      startDate: "Startdatum",
      endDate: "Enddatum",
      responsibilities: "Aufgaben und Erfolge",
      addWorkExperience: "Berufserfahrung hinzufügen",
      education: "Ausbildung",
      educationEntry: "Ausbildung {number}",
      school: "Schule oder Bildungseinrichtung",
      degree: "Abschluss oder Qualifikation",
      fieldOfStudy: "Studienfach",
      details: "Details",
      addEducation: "Ausbildung hinzufügen",
      skills: "Fähigkeiten",
      skillsPlaceholder: "Fähigkeiten durch Kommas getrennt eingeben",
      languages: "Sprachen",
      language: "Sprache",
      languageExample: "z. B. Englisch",
      proficiency: "Sprachniveau",
      proficiencyExample: "Muttersprache, fließend, B2, Grundkenntnisse",
      reorderLanguage: "Sprache {number} neu anordnen",
      dragToReorder: "Zum Sortieren ziehen",
      addLanguage: "Sprache hinzufügen",
      projects: "Projekte",
      project: "Projekt {number}",
      projectName: "Projektname",
      yourRole: "Ihre Rolle",
      projectUrl: "Projekt-URL",
      addProject: "Projekt hinzufügen",
      courses: "Kurse & Zertifikate",
      course: "Kurs {number}",
      courseName: "Kurs oder Zertifikat",
      provider: "Anbieter",
      completionDate: "Abschlussdatum",
      shortDescription: "Kurzbeschreibung",
      coursePlaceholder: "Beschreiben Sie kurz, was Sie gelernt haben",
      addCourse: "Kurs hinzufügen",
      interests: "Interessen & Hobbys",
      interestsPlaceholder:
        "Interessen und Hobbys durch Kommas getrennt eingeben",
      consent: "Einwilligung zur Verarbeitung personenbezogener Daten",
      consentDescription:
        "Diese Klausel informiert das Unternehmen darüber, dass Sie der Verarbeitung Ihrer personenbezogenen Daten für Recruiting und Einstellung zustimmen.",
      consentStatement: "Einwilligungserklärung",
      consentPlaceholder:
        "Ich willige in die Verarbeitung meiner personenbezogenen Daten zu Bewerbungszwecken ein...",
      back: "Zurück",
      invalidImport:
        "Die importierte Datei enthält keine gültigen Lebenslaufdaten.",
      cropTitle: "Profilfoto zuschneiden",
      cropInstructions:
        "Ziehen Sie das Bild, um es auszurichten, und passen Sie dann den Zoom an.",
      closeCrop: "Dialog zum Zuschneiden schließen",
      zoom: "Zoom",
      cancel: "Abbrechen",
      processing: "Wird verarbeitet...",
      usePhoto: "Foto verwenden",
    },
    preview: {
      preparing: "Wird vorbereitet...",
      exportPdf: "Als PDF exportieren",
      liveDocument: "Live-Dokument",
      cvPreview: "Lebenslauf-Vorschau",
      colorway: "Farbschema",
      cvColorway: "Lebenslauf-Farbschema",
      chooseCustomColor: "Benutzerdefinierte Farbe auswählen",
      chooseCustomCvColor: "Benutzerdefinierte Lebenslauffarbe auswählen",
      font: "Schriftart",
      cvFont: "Lebenslauf-Schriftstil",
      fontName: "Schriftart {font}",
      templates: "Lebenslauf-Vorlagen",
      cvPages: "Lebenslaufseiten",
      previousCvPage: "Vorherige Lebenslaufseite",
      previousPage: "Vorherige Seite",
      nextCvPage: "Nächste Lebenslaufseite",
      nextPage: "Nächste Seite",
    },
    colorNames: {
      navy: "Marineblau",
      forest: "Waldgrün",
      burgundy: "Bordeaux",
      charcoal: "Anthrazit",
      teal: "Blaugrün",
      custom: "Benutzerdefiniert",
    },
    fontNames: { formal: "Formal", modern: "Modern", humanist: "Humanistisch" },
    templateNames: {
      modern: "Modern",
      classic: "Klassisch",
      sidebar: "Seitenleiste",
    },
    templateNotes: {
      modern: "Klar und strukturiert",
      classic: "Traditionell und elegant",
      sidebar: "Kompakt und editorial",
    },
  },
  pl: {
    languageNames: {
      en: "Angielski",
      de: "Niemiecki",
      pl: "Polski",
      fr: "Francuski",
    },
    editor: {
      builder: "Kreator CV",
      restart: "Wyczyść",
      restartAria: "Wyczyść i usuń zapisane dane CV",
      save: "Zapisz",
      import: "Importuj",
      importAria: "Importuj zapisane dane CV",
      personalDetails: "Dane osobowe",
      additionalDetails: "Doświadczenie i więcej",
      personalDetailsIntro: "Dodaj dane kontaktowe potrzebne pracodawcom.",
      additionalDetailsIntro:
        "Dodaj doświadczenie, wykształcenie i inne sekcje CV.",
      resumeLanguage: "Język CV",
      fontSize: "Rozmiar czcionki",
      sidebarInset: "Wcięty panel boczny",
      photo: "Zdjęcie profilowe",
      optional: "(opcjonalnie)",
      photoFormats: "JPG, PNG lub WebP. Maksymalnie 15 MB.",
      optimizingImage: "Optymalizowanie obrazu...",
      changePhoto: "Zmień zdjęcie",
      addPhoto: "Dodaj zdjęcie",
      removePhoto: "Usuń zdjęcie",
      photoShape: "Kształt zdjęcia",
      circle: "Koło",
      rectangle: "Prostokąt",
      rounded: "Zaokrąglone",
      photoSize: "Rozmiar zdjęcia",
      border: "Ramka",
      choosePhoto: "Wybierz zdjęcie profilowe",
      chooseJpgPngWebp: "Wybierz obraz JPG, PNG lub WebP.",
      imageTooLarge: "Wybierz obraz mniejszy niż 15 MB.",
      imagePreparationFailed:
        "Nie udało się przygotować tego obrazu. Spróbuj wybrać inny.",
      cropSaveFailed:
        "Nie udało się zapisać kadru. Dopasuj go i spróbuj ponownie.",
      identity: "Dane osobowe",
      requiredFields: "(Pola wymagane oznaczono *)",
      firstName: "Imię",
      firstNameExample: "np. Anna",
      lastName: "Nazwisko",
      lastNameExample: "np. Kowalska",
      professionalTitle: "Stanowisko zawodowe",
      dateOfBirth: "Data urodzenia",
      contact: "Kontakt",
      emailAddress: "Adres e-mail",
      phoneNumber: "Numer telefonu",
      location: "Lokalizacja",
      streetAddress: "Ulica i numer domu",
      streetPlaceholder: "Ulica i numer domu (opcjonalnie)",
      city: "Miasto",
      postalCode: "Kod pocztowy",
      postalCodeExample: "np. 00-001",
      country: "Kraj",
      countryExample: "np. Polska",
      onlinePresence: "Obecność w internecie",
      linkedInProfile: "Profil LinkedIn",
      websitePortfolio: "Strona internetowa lub portfolio",
      next: "Dalej",
      summary: "Podsumowanie zawodowe",
      summaryLabel: "Podsumowanie",
      summaryPlaceholder: "Krótki opis doświadczenia i mocnych stron",
      workExperience: "Doświadczenie zawodowe",
      sortedByDate: "Automatycznie sortowane według daty, od najnowszych.",
      position: "Stanowisko {number}",
      remove: "Usuń",
      jobTitle: "Stanowisko",
      employer: "Pracodawca",
      startDate: "Data rozpoczęcia",
      endDate: "Data zakończenia",
      responsibilities: "Obowiązki i osiągnięcia",
      addWorkExperience: "Dodaj doświadczenie zawodowe",
      education: "Wykształcenie",
      educationEntry: "Wykształcenie {number}",
      school: "Szkoła lub uczelnia",
      degree: "Stopień lub kwalifikacje",
      fieldOfStudy: "Kierunek",
      details: "Szczegóły",
      addEducation: "Dodaj wykształcenie",
      skills: "Umiejętności",
      skillsPlaceholder: "Wpisz umiejętności oddzielone przecinkami",
      languages: "Języki",
      language: "Język",
      languageExample: "np. angielski",
      proficiency: "Poziom znajomości",
      proficiencyExample: "Ojczysty, biegły, B2, komunikatywny",
      reorderLanguage: "Zmień kolejność języka {number}",
      dragToReorder: "Przeciągnij, aby zmienić kolejność",
      addLanguage: "Dodaj język",
      projects: "Projekty",
      project: "Projekt {number}",
      projectName: "Nazwa projektu",
      yourRole: "Twoja rola",
      projectUrl: "Adres projektu",
      addProject: "Dodaj projekt",
      courses: "Kursy i certyfikaty",
      course: "Kurs {number}",
      courseName: "Kurs lub certyfikat",
      provider: "Organizator",
      completionDate: "Data ukończenia",
      shortDescription: "Krótki opis",
      coursePlaceholder: "Krótko opisz zdobytą wiedzę",
      addCourse: "Dodaj kurs",
      interests: "Zainteresowania i hobby",
      interestsPlaceholder: "Wpisz zainteresowania oddzielone przecinkami",
      consent: "Zgoda na przetwarzanie danych osobowych",
      consentDescription:
        "Ta klauzula informuje firmę o zgodzie na przetwarzanie danych osobowych w celach rekrutacyjnych.",
      consentStatement: "Treść zgody",
      consentPlaceholder:
        "Wyrażam zgodę na przetwarzanie moich danych osobowych na potrzeby rekrutacji...",
      back: "Wstecz",
      invalidImport: "Importowany plik nie zawiera prawidłowych danych CV.",
      cropTitle: "Przytnij zdjęcie profilowe",
      cropInstructions:
        "Przeciągnij, aby ustawić zdjęcie, a następnie dopasuj powiększenie.",
      closeCrop: "Zamknij okno przycinania",
      zoom: "Powiększenie",
      cancel: "Anuluj",
      processing: "Przetwarzanie...",
      usePhoto: "Użyj zdjęcia",
    },
    preview: {
      preparing: "Przygotowywanie...",
      exportPdf: "Eksportuj jako PDF",
      liveDocument: "Podgląd na żywo",
      cvPreview: "Podgląd CV",
      colorway: "Kolorystyka",
      cvColorway: "Kolorystyka CV",
      chooseCustomColor: "Wybierz własny kolor",
      chooseCustomCvColor: "Wybierz własny kolor CV",
      font: "Czcionka",
      cvFont: "Styl czcionki CV",
      fontName: "Czcionka: {font}",
      templates: "Szablony CV",
      cvPages: "Strony podglądu CV",
      previousCvPage: "Poprzednia strona CV",
      previousPage: "Poprzednia strona",
      nextCvPage: "Następna strona CV",
      nextPage: "Następna strona",
    },
    colorNames: {
      navy: "Granatowy",
      forest: "Leśna zieleń",
      burgundy: "Bordowy",
      charcoal: "Grafitowy",
      teal: "Morski",
      custom: "Własny",
    },
    fontNames: {
      formal: "Formalny",
      modern: "Nowoczesny",
      humanist: "Humanistyczny",
    },
    templateNames: {
      modern: "Nowoczesny",
      classic: "Klasyczny",
      sidebar: "Boczny panel",
    },
    templateNotes: {
      modern: "Przejrzysty i uporządkowany",
      classic: "Tradycyjny i elegancki",
      sidebar: "Kompaktowy i nowoczesny",
    },
  },
  fr: {
    languageNames: {
      en: "Anglais",
      de: "Allemand",
      pl: "Polonais",
      fr: "Français",
    },
    editor: {
      builder: "Créateur de CV",
      restart: "Réinitialiser",
      restartAria: "Réinitialiser et effacer les données CV enregistrées",
      save: "Enregistrer",
      import: "Importer",
      importAria: "Importer les données CV enregistrées",
      personalDetails: "Informations personnelles",
      additionalDetails: "Expérience et plus",
      personalDetailsIntro:
        "Ajoutez les coordonnées nécessaires aux employeurs.",
      additionalDetailsIntro:
        "Ajoutez votre expérience, votre formation et d’autres rubriques.",
      resumeLanguage: "Langue du CV",
      fontSize: "Taille de police",
      sidebarInset: "Barre latérale en retrait",
      photo: "Photo de profil",
      optional: "(facultatif)",
      photoFormats: "JPG, PNG ou WebP. 15 Mo maximum.",
      optimizingImage: "Optimisation de l’image...",
      changePhoto: "Changer la photo",
      addPhoto: "Ajouter une photo",
      removePhoto: "Supprimer la photo",
      photoShape: "Forme de la photo",
      circle: "Cercle",
      rectangle: "Rectangle",
      rounded: "Arrondie",
      photoSize: "Taille de la photo",
      border: "Bordure",
      choosePhoto: "Choisir une photo de profil",
      chooseJpgPngWebp: "Choisissez une image JPG, PNG ou WebP.",
      imageTooLarge: "Choisissez une image de moins de 15 Mo.",
      imagePreparationFailed:
        "Impossible de préparer cette image. Essayez-en une autre.",
      cropSaveFailed:
        "Impossible d’enregistrer le recadrage. Ajustez-le et réessayez.",
      identity: "Identité",
      requiredFields: "(Les champs obligatoires sont marqués *)",
      firstName: "Prénom",
      firstNameExample: "p. ex. Alex",
      lastName: "Nom",
      lastNameExample: "p. ex. Martin",
      professionalTitle: "Intitulé du poste",
      dateOfBirth: "Date de naissance",
      contact: "Coordonnées",
      emailAddress: "Adresse e-mail",
      phoneNumber: "Téléphone",
      location: "Lieu",
      streetAddress: "Adresse",
      streetPlaceholder: "Rue et numéro (facultatif)",
      city: "Ville",
      postalCode: "Code postal",
      postalCodeExample: "p. ex. 75001",
      country: "Pays",
      countryExample: "p. ex. France",
      onlinePresence: "Présence en ligne",
      linkedInProfile: "Profil LinkedIn",
      websitePortfolio: "Site personnel ou portfolio",
      next: "Suivant",
      summary: "Profil professionnel",
      summaryLabel: "Profil",
      summaryPlaceholder:
        "Une courte présentation de votre expérience et de vos atouts",
      workExperience: "Expérience professionnelle",
      sortedByDate:
        "Tri automatique par date, de la plus récente à la plus ancienne.",
      position: "Poste {number}",
      remove: "Supprimer",
      jobTitle: "Intitulé du poste",
      employer: "Employeur",
      startDate: "Date de début",
      endDate: "Date de fin",
      responsibilities: "Responsabilités et réalisations",
      addWorkExperience: "Ajouter une expérience",
      education: "Formation",
      educationEntry: "Formation {number}",
      school: "Établissement",
      degree: "Diplôme ou qualification",
      fieldOfStudy: "Domaine d’études",
      details: "Détails",
      addEducation: "Ajouter une formation",
      skills: "Compétences",
      skillsPlaceholder: "Séparez les compétences par des virgules",
      languages: "Langues",
      language: "Langue",
      languageExample: "p. ex. anglais",
      proficiency: "Niveau",
      proficiencyExample: "Langue maternelle, courant, B2, conversationnel",
      reorderLanguage: "Réordonner la langue {number}",
      dragToReorder: "Faire glisser pour réordonner",
      addLanguage: "Ajouter une langue",
      projects: "Projets",
      project: "Projet {number}",
      projectName: "Nom du projet",
      yourRole: "Votre rôle",
      projectUrl: "URL du projet",
      addProject: "Ajouter un projet",
      courses: "Cours et certifications",
      course: "Cours {number}",
      courseName: "Cours ou certification",
      provider: "Organisme",
      completionDate: "Date d’obtention",
      shortDescription: "Brève description",
      coursePlaceholder: "Décrivez brièvement ce que vous avez appris",
      addCourse: "Ajouter un cours",
      interests: "Centres d’intérêt et loisirs",
      interestsPlaceholder: "Séparez les centres d’intérêt par des virgules",
      consent: "Consentement au traitement des données personnelles",
      consentDescription:
        "Cette clause informe l’entreprise que vous acceptez le traitement de vos données personnelles à des fins de recrutement.",
      consentStatement: "Texte de consentement",
      consentPlaceholder:
        "J’accepte le traitement de mes données personnelles à des fins de recrutement...",
      back: "Retour",
      invalidImport:
        "Le fichier importé ne contient pas de données CV valides.",
      cropTitle: "Recadrer la photo de profil",
      cropInstructions:
        "Faites glisser pour repositionner, puis réglez le zoom.",
      closeCrop: "Fermer le recadrage",
      zoom: "Zoom",
      cancel: "Annuler",
      processing: "Traitement...",
      usePhoto: "Utiliser la photo",
    },
    preview: {
      preparing: "Préparation...",
      exportPdf: "Exporter en PDF",
      liveDocument: "Document en direct",
      cvPreview: "Aperçu du CV",
      colorway: "Palette de couleurs",
      cvColorway: "Palette du CV",
      chooseCustomColor: "Choisir une couleur personnalisée",
      chooseCustomCvColor: "Choisir une couleur de CV personnalisée",
      font: "Police",
      cvFont: "Style de police du CV",
      fontName: "Police {font}",
      templates: "Modèles de CV",
      cvPages: "Pages d’aperçu du CV",
      previousCvPage: "Page précédente du CV",
      previousPage: "Page précédente",
      nextCvPage: "Page suivante du CV",
      nextPage: "Page suivante",
    },
    colorNames: {
      navy: "Bleu marine",
      forest: "Vert forêt",
      burgundy: "Bordeaux",
      charcoal: "Anthracite",
      teal: "Sarcelle",
      custom: "Personnalisée",
    },
    fontNames: { formal: "Formelle", modern: "Moderne", humanist: "Humaniste" },
    templateNames: {
      modern: "Moderne",
      classic: "Classique",
      sidebar: "Colonne latérale",
    },
    templateNotes: {
      modern: "Épuré et structuré",
      classic: "Traditionnel et raffiné",
      sidebar: "Compact et éditorial",
    },
  },
};

export type TranslationCatalog = WidenStrings<typeof englishStrings>;
